trigger:
  - master
  - dev
  - uat

pool:
  name: Default
  demands:
    - Agent.Name -equals vm-azuredevops

variables:
  appDirectoryDev: "/var/java/dev/"
  appDirectoryUat: "/var/java/uat/"
  appDirectoryProd: "/var/java/prod/"
  jarFileName: "java-helloworld-0.0.1-SNAPSHOT.jar"

stages:
  - stage: Deploy
    displayName: "Deploy Stage"
    jobs:
      - job: DeployToDev
        displayName: "Deploy to Dev"
        condition: eq(variables['Build.SourceBranchName'], 'dev')
        steps:
          - checkout: self
          - script: |
              echo "Deploying to Dev"
              /opt/apache-maven-3.9.6/bin/mvn clean package
              sudo kill -15 $(ps -ef |grep nohup|grep 7070|awk '{print $2}')
              cp -f $(Pipeline.Workspace)/s/target/$(jarFileName) $(appDirectoryDev)
              sudo nohup java -jar $(appDirectoryDev)$(jarFileName) --server.port=7070 > $(appDirectoryDev)dev.log 2>&1 &
            displayName: "Deploy to Dev"

      - job: DeployToUAT
        displayName: "Deploy to UAT"
        condition: eq(variables['Build.SourceBranchName'], 'uat')
        steps:
          - checkout: self
          - script: |
              echo "Deploying to UAT"
              docker compose -f docker-compose-uat.yml build --no-cache
              docker compose -f docker-compose-uat.yml down
              docker compose -f docker-compose-uat.yml up -d
            displayName: "Deploy to UAT"

      - job: DeployToProd
        displayName: "Deploy to Prod"
        condition: eq(variables['Build.SourceBranchName'], 'master')
        steps:
          - checkout: self
          - script: |
              echo "Deploying to Prod"
              /opt/apache-maven-3.9.6/bin/mvn clean package
              sudo kill -15 $(ps -ef |grep nohup|grep 8080|awk '{print $2}')
              cp -f $(Pipeline.Workspace)/s/target/$(jarFileName) $(appDirectoryProd)
              sudo nohup java -jar $(appDirectoryProd)$(jarFileName) > $(appDirectoryDev)prod.log 2>&1 &
            displayName: "Deploy to Prod"
