trigger:
  - master
  - dev
  - uat

pool:
  name: Default
  demands:
    - Agent.Name -equals vm-azuredevops

stages:
  - stage: Deploy
    displayName: "Deploy Stage"
    jobs:
      - job: DeployToDev
        displayName: "Deploy to Dev"
        condition: eq(variables['Build.SourceBranchName'], 'dev')
        steps:
          - checkout: self
          - script: |
              echo "Deploying to Dev"              
              ansible-playbook $(Pipeline.Workspace)/s/playbook.yml -i $(Pipeline.Workspace)/s/hosts -e branch=$(Build.SourceBranchName) -e work_space=$(Pipeline.Workspace)/s/ --limit local
            displayName: "Deploy to Dev"

      - job: DeployToUAT
        displayName: "Deploy to UAT"
        condition: eq(variables['Build.SourceBranchName'], 'uat')
        steps:
          - checkout: self
          - script: |
              echo "Deploying to UAT"
              ansible-playbook $(Pipeline.Workspace)/s/playbook.yml -i $(Pipeline.Workspace)/s/hosts -e branch=$(Build.SourceBranchName) -e work_space=$(Pipeline.Workspace)/s/ --limit local
            displayName: "Deploy to UAT"

      - job: DeployToProd
        displayName: "Deploy to Prod"
        condition: eq(variables['Build.SourceBranchName'], 'master')
        steps:
          - checkout: self
          - script: |
              echo "Deploying to Prod"
              ansible-playbook $(Pipeline.Workspace)/s/playbook.yml -i $(Pipeline.Workspace)/s/hosts -e branch=$(Build.SourceBranchName) -e work_space=$(Pipeline.Workspace)/s/ --limit local
            displayName: "Deploy to Prod"
