---
- hosts: all
  become: true
  gather_facts: false
  become_method: sudo
  become_user: root
  tasks:
    - name: "DOCKER COMPOSE BUILD IMAGES"
      command:
        cmd: "docker compose -f docker-compose-{{ branch }}.yml build --no-cache"
        chdir: "{{ work_space }}"

    - name: "DOCKER COMPOSE STOP OLD CONTAINERS"
      command:
        cmd: "docker compose -f docker-compose-{{ branch }}.yml down"
        chdir: "{{ work_space }}"
      ignore_errors: yes

    - name: "DOCKER COMPOSE START ALL CONTAINERS"
      command:
        cmd: "docker compose -f docker-compose-{{ branch }}.yml up -d"
        chdir: "{{ work_space }}"
